FORMAT: 1A
HOST: http://odn-backend.herokuapp.com/

# ODN API

The ODN API exposes all functionality in the opendatanetwork.com


## Relatives [/related/{relation}{?id}{?limit}]

Find entities that are related to one another.


The current hierarchy of entities is listed below,
where "a > b" means that a is a parent of b.
Note that some entities, like metropolitan areas, may have multiple parents.
For example, the New York metropolitan area lies within the states of New York,
New Jersey, and Pennsylvania.

```
nation > region
region > division
division > state
state > county
state > msa
state > place
```

TODO: update with link to relation file on odn-backend when available

Entities are grouped by type and sorted in descending order by their rank.
For example, region entities are sorted in descending order by population.

+ Parameters
    + relation (required, string, `parent`)

        The type of relation to find.

        + Values
            + `parent`
            + `child`
            + `sibling`
            + `peer`

    + id (required, string, `0400000US53`)

        ID of the target entity.

    + limit (optional, number)

        Maximum number of entities in each group.
        Must be an integer from 1 to 1000.

        + Default: `10`

### Find the relatives of an entity [GET]

+ Request

    Get the parent region of Washington state.
    
    - Parameters
        - relation: parent
        - id: 0400000US53

+ Response 200 (application/json)

        {
            "entity": {
                "id": "0400000US53",
                "name": "Washington",
                "type": "state"
            },

            "groups": [
                {
                    "type": "division",
                    "entities": [
                        {
                            "id": "0300000US9",
                            "name": "Pacific Division",
                            "type": "division"
                        }
                    ]
                }
            ]
        }
        
## Topics [/topic{?id}]

Returns a tree of all topics that have data for the given entities.

+ Parameters
    + id (required, string, `0100000US-0400000US53`)
    
        Hyphen-separated list of entity IDs.

### Find the data available for some entities [GET]

+ Request

    Get data that is available for both the United States and Washington State.
    
    - Parameters
        - id: 0100000US-0400000US53
    
+ Response 200 (application/json)

        {
            "entities": [
                {
                    "id": "0100000US",
                    "name": "United States",
                    "type": "region.nation"
                },
                {
                    "id": "0400000US53",
                    "name": "Washington",
                    "type": "region.state"
                }
            ],
            "topics": [
                {
                    "id": "demographics",
                    "name": "Demographics",
                    "type": "root",
                    "topics": [
                        {
                            "id": "demographics.population",
                            "name": "Population",
                            "type": "topic",
                            "topics": [
                                {
                                    "id": "demographics.population.count",
                                    "name": "Population Count",
                                    "type": "variable",
                                    "did": "1234-abcd",
                                    "topics": [
                                        {
                                            "id": "demographics.population.count.year",
                                            "name": "Year",
                                            "type": "constraint"
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }