FORMAT: 1A
HOST: http://odn-backend.herokuapp.com/

# ODN API

The ODN REST API exposes public data and functionality available on OpenDataNetwork.com provided by
hundreds of government and other public sector agencies.
In addition to search and autosuggest capabilities in finding datasets, the ODN API exposes detailed
entity level data which enables data based comparisons across geographical regions such as states,
counties, metropolitan areas, cities and zip codes using highly vetted data providers such as US Census,
BEA, HUD and others. The ODN API does not duplicate API endpoints or services provided by public sector
agencies, but rather, returns context relevant pre-populated REST URLs so the caller can access the
data directly from the source.

## App Tokens

Registering for and including a [Socrata application token](https://dev.socrata.com/docs/app-tokens.html)
grants you a much higher quota of API requests. They can be passed either using the `app_token` parameter
or the `X-App-Token` HTTP header.

## Relatives [/related/v1/{relation}{?entity_id}{?limit}{?app_token}]

Find entities that are related to one another.

The current hierarchy of entities is listed below,
where "a > b" means that a is a parent of b.
Note that some entities, like metropolitan areas, may have multiple parents.
For example, the New York metropolitan area lies within the states of New York,
New Jersey, and Pennsylvania.

```
nation > region
region > division
division > state
state > county
state > msa
state > place
```

TODO: update with link to relation file on odn-backend when available

Entities are grouped by type and sorted in descending order by their rank.
For example, region entities are sorted in descending order by population.

+ Parameters
    + relation (required, string, `parent`)

        The type of relation to find.

        + Values
            + `parent`
            + `child`
            + `sibling`
            + `peer`

    + entity_id (required, string, `0400000US53`)

        ID of the target entity.

    + limit (optional, number)

        Maximum number of entities in each group.
        Must be an integer from 1 to 1000.

        + Default: `10`

    + app_token (optional, string)

        The [Socrata App Token](https://dev.socrata.com/docs/app-tokens.html) to be
        used with your request. Can also be passed via the `X-App-Token` HTTP header.

### Find the relatives of an entity [GET]

+ Request

    Get the parent region of Washington state.

    - Parameters
        - relation: parent
        - entity_id: 0400000US53

    - Headers

            X-App-Token: cQovpGcdUT1CSzgYk0KPYdAI0

+ Response 200 (application/json)

        {
            "relatives": [
                {
                    "type": "region.division",
                    "entities": [
                        {
                            "id": "0300000US9",
                            "name": "Pacific Division",
                            "type": "region.division"
                        }
                    ]
                }
            ]
        }

## Data Availability [/data/v1/availability/{?entity_id}{?app_token}]

Find all of the topics, datasets, and variables that have data
for all of the given entities.

+ Parameters
    + entity_id (required, string, `0100000US,0400000US53`)

        Comma separated list of entity IDs.

    + app_token (optional, string)

        The [Socrata App Token](https://dev.socrata.com/docs/app-tokens.html) to be
        used with your request. Can also be passed via the `X-App-Token` HTTP header.

### Find all available data for some entities [GET]

+ Request

    Get variables that have data for both the United States and Washington State.

    - Parameters
        - entity_id: 0100000US,0400000US53

    - Headers

            X-App-Token: cQovpGcdUT1CSzgYk0KPYdAI0

+ Response 200 (application/json)

        {
            "topics": {
                "demographics": {
                    "id": "demographics",
                    "name": "Demographics",
                    "datasets": {
                        "population": {
                            "fxf": "9jg8-ki9x",
                            "constraints": [
                                "year"
                            ],
                            "searchTerms": [
                                "population",
                                "household",
                                "demographics",
                                "ethnicity",
                                "minority"
                            ],
                            "sources": [
                                {
                                    "name": "U.S. Census American Community Survey",
                                    "url": "https://www.census.gov/programs-surveys/acs/"
                                }
                            ],
                            "id": "demographics.population",
                            "domain": "odn.data.socrata.com",
                            "description": "",
                            "url": "https://odn.data.socrata.com/resource/9jg8-ki9x.json",
                            "name": "Population",
                            "variables": {
                                "change": {
                                    "name": "Population Change",
                                    "description": "Percent change from the previous year",
                                    "id": "demographics.population.change",
                                    "url": "https://odn.data.socrata.com/resource/9jg8-ki9x.json?variable=change&%24where=id%20in('0100000US'%2C'0400000US53')"
                                },
                                "count": {
                                    "name": "Population Count",
                                    "id": "demographics.population.count",
                                    "url": "https://odn.data.socrata.com/resource/9jg8-ki9x.json?variable=count&%24where=id%20in('0100000US'%2C'0400000US53')"
                                }
                            }
                        }
                    }
                }
            }
        }

## Data Constraints [/data/v1/constraint/{variable}{?entity_id}{?constraint}{?app_token}]

Get constraints for the given variable and entities.

+ Parameters
    + variable (required, string, `demographics.population.count`)

        Full ID of the variable to retrieve.

    + entity_id (required, string, `0100000US,0400000US53`)

        Comma separated list of entity IDs.

    + constraint (required, string, `year`)

        Constraint to use.

    + app_token (optional, string)

        The [Socrata App Token](https://dev.socrata.com/docs/app-tokens.html) to be
        used with your request. Can also be passed via the `X-App-Token` HTTP header.


### Get constraint permutations for entities [GET]

+ Request

    Get all the years that have population count data for the United States
    and Washington state.

    - Parameters
        - entity_id: 0100000US,0400000US53
        - variable: demographics.population.count
        - constraint: year

    - Headers

            X-App-Token: cQovpGcdUT1CSzgYk0KPYdAI0

+ Response 200 (application/json)

        {
          "permutations": [
            {
              "constraint_value": "2009",
              "constraint_url": "https://odn.data.socrata.com/resource/9jg8-ki9x.json?variable=count&%24where=id%20in('0100000US'%2C'0400000US53')&year=2009"
            },
            {
              "constraint_value": "2010",
              "constraint_url": "https://odn.data.socrata.com/resource/9jg8-ki9x.json?variable=count&%24where=id%20in('0100000US'%2C'0400000US53')&year=2010"
            },
            {
              "constraint_value": "2011",
              "constraint_url": "https://odn.data.socrata.com/resource/9jg8-ki9x.json?variable=count&%24where=id%20in('0100000US'%2C'0400000US53')&year=2011"
            },
            {
              "constraint_value": "2012",
              "constraint_url": "https://odn.data.socrata.com/resource/9jg8-ki9x.json?variable=count&%24where=id%20in('0100000US'%2C'0400000US53')&year=2012"
            },
            {
              "constraint_value": "2013",
              "constraint_url": "https://odn.data.socrata.com/resource/9jg8-ki9x.json?variable=count&%24where=id%20in('0100000US'%2C'0400000US53')&year=2013"
            }
          ]
        }

## Data Values [/data/v1/values{?variable}{?entity_id}{?constraint}{?forecast}{?describe}{?app_token}]

Retrieve the values for available data about entities.

+ Parameters

    + variable (required, string, `demographics.population.count`)

        Comma separated list of variable IDs.
        Defaults to retrieving all variables.
        It is also possible to pass in a topic such as
        `demographics`, or a dataset such as `demographics.population`,
        which would both be equivalent to specifying
        `demographics.population.count` and `demographics.population.change`.
        Note that only variables in the same dataset are allowed.

    + entity_id (optional, string, `0100000US,0400000US53`)

        Comma separated list of entity IDs.
        Defaults to retrieving all entities.
        Note that since there is currently no results pagination,
        retrieving values for all entities may produce incomplete results.

    + constraint (optional, string)
    
        To retrieve values for multiple variables, values must be specified
        for every constraint in the dataset. For example, to get all of the variables
        in the `jobs.occupations` dataset, we would need to specify values
        for both `year` and `occupation` by setting passing `year=2013` and
        `occupation=Engineering`.
        
    + forecast (optional, number)

        Number of steps to forecast.
        Must be an integer between 0 and 20.
        Forecasts are produced using linear extrapolation
        on the data. They are only available when retrieving
        data for a single variable across many numerical
        constraint options.

        + Default `0`

    + describe (optional, boolean)

        Whether or not to produce a description of the data.
        Set to `true` to produce a description.
        Descriptions are not available if no entities are specified.

        + Default `false`

    + app_token (optional, string)

        The [Socrata App Token](https://dev.socrata.com/docs/app-tokens.html) to be
        used with your request. Can also be passed via the `X-App-Token` HTTP header.

### Get values [GET]

+ Request

    Get the annual populations of the United States and Washington and
    forecast 3 years into the future.

    - Parameters
        - entity_id: 0100000US,0400000US53
        - variable: demographics.population.count
        - forecast: 3
        - describe: true
   
    - Headers

            X-App-Token: cQovpGcdUT1CSzgYk0KPYdAI0

+ Response 200 (application/json)

        {
            "data": [
                [
                    "year",
                    "0100000US",
                    "0400000US53",
                    "forecast"
                ],
                [
                    2009,
                    301461533,
                    6465755,
                    false
                ],
                [
                    2010,
                    303965272,
                    6561297,
                    false
                ],
                [
                    2011,
                    306603772,
                    6652845,
                    false
                ],
                [
                    2012,
                    309138711,
                    6738714,
                    false
                ],
                [
                    2013,
                    311536594,
                    6819579,
                    false
                ],
                [
                    2014,
                    314055359.25,
                    6908035,
                    true
                ],
                [
                    2015,
                    316574124.5,
                    6996491,
                    true
                ],
                [
                    2016,
                    319092889.75,
                    7084947,
                    true
                ]
            ],
            "forecast_info": {
                "algorithm_name": "linear",
                "algorithm_url": "https://en.wikipedia.org/wiki/Extrapolation#Linear_extrapolation"
            }
        }

## Suggestions [/suggest/v1/{type}{?query}{?limit}{?app_token}]

Suggests entities like geographical regions, questions, datasets, publishers and categories
that match the given query prefix or full phrase. Useful for building autosuggest style query 
interaction where suggestions are provided as a user types.

+ Parameters
    + type (required, string, `entity`)

        Type of the object to find.

        + Values
            + `entity`
            + `category`
            + `publisher`
            + `dataset`
            + `question`

    + query (required, string, `seattl`)

        Query to match.

    + limit (optional, number)

        Maximum number of results to return.
        Must be an integer from 1 to 100.

        + Default: `5`

    + app_token (optional, string)

        The [Socrata App Token](https://dev.socrata.com/docs/app-tokens.html) to be
        used with your request. Can also be passed via the `X-App-Token` HTTP header.

### Get suggestions [GET]

+ Request

    Suggest entities that match "seattl".

    - Parameters
        - type: entity
        - query: seattl

    - Headers

            X-App-Token: cQovpGcdUT1CSzgYk0KPYdAI0

+ Response 200 (application/json)

        {
            "entities": [
                {
                    "id": "310M200US42660",
                    "name": "Seattle Metro Area (WA)",
                    "type": "regions.msa"
                },
                {
                    "id": "1600000US5363000",
                    "name": "Seattle, WA",
                    "type": "regions.place"
                }
            ]
        }